# Production configuration for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  # Production backend
  app:
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    # No bind mounts in production - use volumes only
    volumes:
      - app-data:/var/www/html
      
  # Production frontend (built during image creation)
  frontend:
    # No development volumes in production
    environment:
      - NODE_ENV=production

  # Production database
  mysql:
    # Don't expose MySQL port in production
    # ports: []  # Remove external port exposure
    volumes:
      - mysql_prod_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --default-time-zone=+08:00
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=512M
      --innodb-flush-log-at-trx-commit=1
      --innodb-flush-method=O_DIRECT
      --max-connections=500
      --slow-query-log=1
      --long-query-time=1

volumes:
  mysql_prod_data: