# Production Docker Compose configuration for clinic management system

services:
  # Backend PHP/Symfony Application
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - app-data:/var/www/html
      - ./config/jwt:/var/www/html/config/jwt:ro
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://clinic_user:clinic_password@mysql:3306/clinic_db?serverVersion=8.0
      - TZ=Asia/Kuala_Lumpur
      - JWT_SECRET_KEY=/var/www/html/config/jwt/private.pem
      - JWT_PUBLIC_KEY=/var/www/html/config/jwt/public.pem
      - JWT_PASSPHRASE=0769fa69cb42c84beedcfc421bd5ff638be91715fa4987b71afd2dd1a845077a
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - clinic-network
    restart: unless-stopped
    expose:
      - "9000"
    # healthcheck:
    #   test: ["CMD", "/usr/local/bin/healthcheck.sh"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    command: ["/usr/local/bin/startup-prod.sh"]

  # Frontend Vue.js Application
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - "80"
    depends_on:
      - app
    networks:
      - clinic-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "0.0.0.0:8090:80"
    depends_on:
      app:
        condition: service_healthy
      frontend:
        condition: service_started  
    networks:
      - clinic-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-clinic_password}
      TZ: Asia/Kuala_Lumpur
    ports:
      - "0.0.0.0:3307:3306"
    networks:
      - clinic-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./COMPLETE_DATABASE_SETUP.sql:/docker-entrypoint-initdb.d/setup.sql:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --default-time-zone=+08:00
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=512M
      --innodb-log-buffer-size=32M
      --innodb-flush-log-at-trx-commit=1
      --innodb-flush-method=O_DIRECT
      --max-connections=500
      --thread-cache-size=100
      --table-open-cache=8000
      --tmp-table-size=128M
      --max-heap-table-size=128M
      --sort-buffer-size=4M
      --join-buffer-size=4M
      --key-buffer-size=64M
      --read-buffer-size=2M
      --read-rnd-buffer-size=4M
      --bulk-insert-buffer-size=32M
      --myisam-sort-buffer-size=64M
      --wait-timeout=600
      --interactive-timeout=600
      --connect-timeout=30
      --lock-wait-timeout=300
      --innodb-lock-wait-timeout=300
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=1
      --log-queries-not-using-indexes=1
      --innodb-thread-concurrency=0
      --innodb-read-io-threads=16
      --innodb-write-io-threads=16
      --innodb-io-capacity=2000
      --innodb-io-capacity-max=4000
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "clinic_user", "-p${MYSQL_PASSWORD:-clinic_password}"]
      timeout: 10s
      interval: 30s
      retries: 5

volumes:
  app-data:
    driver: local
  mysql_data:
    driver: local

networks:
  clinic-network:
    driver: bridge